name: Build and Test
on: [push, pull_request]
jobs:
  # XXX: macOS, Windows
  ubuntu:
    strategy:
      matrix:
          version: ['7.3', '7.4', '8.0', '8.1']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache DB2 library
        id: cache-clidriver
        uses: actions/cache@v2
        with:
          path: clidriver
          key: ${{ runner.os }}-clidriver
      - name: Install DB2 library
        if: steps.cache-clidriver.outputs.cache-hit != 'true'
        run: |
          wget https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
          tar xvzf linuxx64_odbc_cli.tar.gz
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.version}}
          extensions: pdo
      - name: Build PDO_IBM
        run: |
          phpize
          ./configure --with-pdo-ibm=$PWD/clidriver
          make
      # XXX: No tests until DB2 Docker container is set up (see Travis)
      #- name: Test dbase
      #  run: make test TESTS=tests
